# Generated by Django 3.1.2 on 2021-04-10 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='agent',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='estate',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
    ]
