# Generated by Django 3.1.2 on 2021-04-10 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0002_auto_20210411_0126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='agent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='estate',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
    ]
