# Generated by Django 3.1.2 on 2021-04-10 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0003_auto_20210411_0155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={},
        ),
        migrations.AlterModelOptions(
            name='agent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='estate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
